name: Build Jekyll

on:
  push:
    branches:
      - jekyll-setup

jobs:
  build-jekyll:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - uses: helaili/jekyll-action@v2
      with:
        token: ${{ secrets.JEKYLL_PAT }}
        target_branch: gh-pages
        
