name: publish

on: 
  push:
    tags:
      - '*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setting up Node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm test
      - run: npm run mutation-test
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true
      - name: Publish as ${{steps.tag.outputs.tag}} Unit Test Coverage (Jest)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage
          destination_dir: ./unit-test-coverage-reports/${{steps.tag.outputs.tag}}
      - name: Publish as latest Unit Test Coverage (Jest)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage
          destination_dir: ./unit-test-coverage-reports/latest
      - name: Publish as latest Mutation Test Coverage (Stryker)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports/mutation/html
          destination_dir: ./mutation-test-coverage-reports/latest
      - name: Publish as ${{steps.tag.outputs.tag}} Mutation Test Coverage (Stryker)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports/mutation/html
          destination_dir: ./mutation-test-coverage-reports/${{steps.tag.outputs.tag}}
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}
          access: public
